# Generated by Django 5.2.6 on 2025-10-04 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(default='ALGO', max_length=10)),
                ('to_currency', models.CharField(default='USDC', max_length=10)),
                ('amount_in', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_out', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('slippage', models.DecimalField(decimal_places=2, default=0.03, max_digits=5)),
                ('tx_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.transaction')),
            ],
        ),
    ]
