# Generated by Django 5.2.6 on 2025-11-19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE payments_transaction
                ALTER COLUMN usdc_received TYPE numeric(12, 6)
                USING CASE
                    WHEN usdc_received IS NULL THEN NULL
                    WHEN usdc_received = TRUE THEN 1
                    ELSE 0
                END
            """,
            reverse_sql="""
                ALTER TABLE payments_transaction
                ALTER COLUMN usdc_received TYPE boolean
                USING CASE
                    WHEN usdc_received IS NULL THEN NULL
                    WHEN usdc_received <> 0 THEN TRUE
                    ELSE FALSE
                END
            """,
        ),
    ]
