# Generated by Django 5.2.6 on 2025-10-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_usdc_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='swap_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('ALGO', 'Algorand'), ('USDC', 'USDC (Algorand)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('subscription', 'New Subscription'), ('renewal', 'Renewal'), ('manual', 'Manual Payment')], max_length=20),
        ),
    ]
