# Generated by Django 5.2.6 on 2025-11-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_swap_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payout_tx_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_fee_tx_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
