# Generated by Django 5.2.6 on 2025-10-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
