# Generated by Django 5.2.6 on 2025-10-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhooklog_error_message_webhooklog_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['endpoint', 'external_id'], name='webhooks_we_endpoin_5907be_idx'),
        ),
    ]
