# Generated by Django 5.2.6 on 2025-10-27 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='integration',
            name='endpoint_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='integration',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='last_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='integration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='IntegrationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.integration')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
