# Generated by Django 5.2.6 on 2025-10-28 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integrations", "0002_integration_auth_token_integration_endpoint_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndpointPricingRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pattern", models.CharField(max_length=255)),
                ("methods", models.JSONField(blank=True, default=list)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("currency", models.CharField(default="USDC", max_length=12)),
                ("network", models.CharField(default="algorand", max_length=32)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="x402_pricing_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "pattern"),
            },
        ),
        migrations.AddIndex(
            model_name="endpointpricingrule",
            index=models.Index(fields=["user", "priority"], name="integrations_user_prio_364458_idx"),
        ),
        migrations.AddIndex(
            model_name="endpointpricingrule",
            index=models.Index(fields=["user", "pattern"], name="integrations_user_patte_61b1ca_idx"),
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nonce", models.CharField(max_length=128, unique=True)),
                ("receipt_token", models.TextField(blank=True)),
                ("payer_address", models.CharField(blank=True, max_length=128)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("currency", models.CharField(default="USDC", max_length=12)),
                ("network", models.CharField(default="algorand", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("request_path", models.CharField(max_length=255)),
                ("request_method", models.CharField(default="GET", max_length=10)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="x402_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(fields=["user", "status"], name="integrations_user_statu_fb96a5_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(fields=["request_path", "status"], name="integrations_request_9f3a6d_idx"),
        ),
    ]
