# Generated by ChatGPT on 2025-10-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integrations", "0003_paymentreceipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("link", "Payment link"), ("widget", "Embedded widget")], default="link", max_length=16)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("currency", models.CharField(default="USDC", max_length=12)),
                ("network", models.CharField(default="algorand", max_length=32)),
                ("pattern", models.CharField(editable=False, max_length=255)),
                ("success_url", models.URLField(blank=True)),
                ("callback_url", models.URLField(blank=True)),
                ("pay_to_address", models.CharField(blank=True, max_length=128)),
                ("platform_fee_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_links", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=("user", "slug"), name="paymentlink_user_slug"),
                    models.Index(fields=("user", "kind", "is_active"), name="paymentlink_active_idx"),
                ],
                "unique_together": {("user", "slug")},
            },
        ),
        migrations.CreateModel(
            name="PaymentLinkEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payer_address", models.CharField(blank=True, max_length=128)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("fee_amount", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ("merchant_amount", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "link",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="integrations.paymentlink"),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="link_events",
                        to="integrations.paymentreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=("link", "created_at"), name="linkevent_created_idx"),
                    models.Index(fields=("payer_address",), name="linkevent_payer_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="X402CreditPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("currency", models.CharField(default="USDC", max_length=12)),
                ("network", models.CharField(default="algorand", max_length=32)),
                ("credits_per_payment", models.PositiveIntegerField(default=1)),
                ("auto_renew", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("pattern", models.CharField(editable=False, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("pay_to_address", models.CharField(blank=True, max_length=128)),
                ("platform_fee_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="x402_credit_plans", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=("user", "slug"), name="creditplan_user_slug"),
                    models.Index(fields=("user", "is_active"), name="creditplan_active_idx"),
                ],
                "unique_together": {("user", "slug")},
            },
        ),
        migrations.CreateModel(
            name="CreditSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("consumer_ref", models.CharField(max_length=160)),
                ("credits_remaining", models.IntegerField(default=0)),
                ("total_credits", models.IntegerField(default=0)),
                ("last_purchase_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="integrations.x402creditplan"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=("plan", "consumer_ref"), name="creditsub_plan_consumer"),
                    models.Index(fields=("consumer_ref",), name="creditsub_consumer_idx"),
                ],
                "unique_together": {("plan", "consumer_ref")},
            },
        ),
        migrations.CreateModel(
            name="CreditUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "usage_type",
                    models.CharField(
                        choices=[("top_up", "Top-up"), ("consumption", "Consumption")],
                        default="top_up",
                        max_length=16,
                    ),
                ),
                ("credits_delta", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("fee_amount", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ("merchant_amount", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_usages",
                        to="integrations.paymentreceipt",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="usages", to="integrations.creditsubscription"),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=("subscription", "created_at"), name="creditusage_created_idx"),
                ],
            },
        ),
        migrations.AlterUniqueTogether(name="endpointpricingrule", unique_together={("user", "pattern")}),
    ]
