# Generated by Django 5.2.6 on 2025-11-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_paymentlink_creditplan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditsubscription',
            new_name='integration_plan_id_d8db1b_idx',
            old_name='creditsub_plan_consumer',
        ),
        migrations.RenameIndex(
            model_name='creditsubscription',
            new_name='integration_consume_1f6021_idx',
            old_name='creditsub_consumer_idx',
        ),
        migrations.RenameIndex(
            model_name='creditusage',
            new_name='integration_subscri_d1d174_idx',
            old_name='creditusage_created_idx',
        ),
        migrations.RenameIndex(
            model_name='endpointpricingrule',
            new_name='integration_user_id_dc28ed_idx',
            old_name='integrations_user_prio_364458_idx',
        ),
        migrations.RenameIndex(
            model_name='endpointpricingrule',
            new_name='integration_user_id_cc4931_idx',
            old_name='integrations_user_patte_61b1ca_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentlink',
            new_name='integration_user_id_8d30e8_idx',
            old_name='paymentlink_user_slug',
        ),
        migrations.RenameIndex(
            model_name='paymentlink',
            new_name='integration_user_id_b6fb4b_idx',
            old_name='paymentlink_active_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentlinkevent',
            new_name='integration_link_id_bf9b29_idx',
            old_name='linkevent_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentlinkevent',
            new_name='integration_payer_a_c6573a_idx',
            old_name='linkevent_payer_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreceipt',
            new_name='integration_user_id_0a4375_idx',
            old_name='integrations_user_statu_fb96a5_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreceipt',
            new_name='integration_request_d35b7e_idx',
            old_name='integrations_request_9f3a6d_idx',
        ),
        migrations.RenameIndex(
            model_name='x402creditplan',
            new_name='integration_user_id_68243e_idx',
            old_name='creditplan_user_slug',
        ),
        migrations.RenameIndex(
            model_name='x402creditplan',
            new_name='integration_user_id_170484_idx',
            old_name='creditplan_active_idx',
        ),
    ]
