# Generated by Django 5.2.6 on 2025-10-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_checkoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='contract_app_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Algorand app ID for on-chain enforcement', null=True),
        ),
    ]
