# Generated by Django 5.2.6 on 2025-11-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_checkoutsession_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='payout_wallet_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
